--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NintendoCore16/slots-infinitos-Genisys-Pocketmine
branches:
- master
projects:
  slots-infinitos-Genisys-Pocketmine:
    path: ""
...
